In [1]:
import numpy as np

In [2]:
rewards = np.zeros((6, 6))

In [3]:
for state in range(6):
    for action in range(6):
        rewards[state][action] = -1

In [4]:
q_table = np.zeros((6, 6))

In [5]:
rewards[1][5] = 100

In [6]:
rewards[4][5] = 100
rewards[5][5] = 100

In [7]:
rewards[0][4] = 0
rewards[1][3] = 0
rewards[2][3] = 0
rewards[3][1] = 0
rewards[3][2] = 0
rewards[3][4] = 0
rewards[4][0] = 0
rewards[4][3] = 0
rewards[5][1] = 0
rewards[5][4] = 0

In [8]:
rewards

array([[ -1.,  -1.,  -1.,  -1.,   0.,  -1.],
       [ -1.,  -1.,  -1.,   0.,  -1., 100.],
       [ -1.,  -1.,  -1.,   0.,  -1.,  -1.],
       [ -1.,   0.,   0.,  -1.,   0.,  -1.],
       [  0.,  -1.,  -1.,   0.,  -1., 100.],
       [ -1.,   0.,  -1.,  -1.,   0., 100.]])

In [9]:
gamma = 0.8

In [10]:
q_table = np.zeros((6, 6))

In [11]:
def train_agent():  
    my_list = []
    for state in range(6):
        for action in range(6):
            if(rewards[state][action] != -1):
                for next_possible_action in range(6):
                        if (rewards[action][next_possible_action] != -1):
                            my_list.append(q_table[action][next_possible_action])
                if len(my_list) > 0:  
                    max_value = max(my_list)
                    print(max_value)
                    q_table[state][action] = int(rewards[state][action] + gamma*max_value)
                    my_list = []

In [12]:
train_agent()
q_table

0.0
0.0
0.0
0.0
100.0
0.0
0.0
0.0
80.0
0.0
100.0
100.0
80.0


array([[  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  80.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  64.,   0., 100.],
       [  0.,  80.,   0.,   0.,  80., 164.]])

In [13]:
for training_iteration in range(30):
    print("Iteration: ", training_iteration)
    train_agent()
    print(q_table)

Iteration:  0
100.0
80.0
164.0
80.0
231.0
64.0
100.0
80.0
184.0
164.0
231.0
231.0
184.0
[[  0.   0.   0.   0.  80.   0.]
 [  0.   0.   0.  64.   0. 231.]
 [  0.   0.   0.  64.   0.   0.]
 [  0. 184.  51.   0.  80.   0.]
 [ 64.   0.   0. 147.   0. 231.]
 [  0. 184.   0.   0. 184. 247.]]
Iteration:  1
231.0
184.0
247.0
184.0
297.0
147.0
231.0
184.0
237.0
247.0
297.0
297.0
247.0
[[  0.   0.   0.   0. 184.   0.]
 [  0.   0.   0. 147.   0. 297.]
 [  0.   0.   0. 147.   0.   0.]
 [  0. 237. 117.   0. 184.   0.]
 [147.   0.   0. 189.   0. 297.]
 [  0. 237.   0.   0. 237. 297.]]
Iteration:  2
297.0
237.0
297.0
237.0
337.0
189.0
297.0
237.0
269.0
297.0
337.0
337.0
297.0
[[  0.   0.   0.   0. 237.   0.]
 [  0.   0.   0. 189.   0. 337.]
 [  0.   0.   0. 189.   0.   0.]
 [  0. 269. 151.   0. 237.   0.]
 [189.   0.   0. 215.   0. 337.]
 [  0. 269.   0.   0. 269. 337.]]
Iteration:  3
337.0
269.0
337.0
269.0
369.0
215.0
337.0
269.0
295.0
337.0
369.0
369.0
337.0
[[  0.   0.   0.   0. 269.   0.]
 [  0.

 | S/A  | A  | B  | C  | D  |  E  | F |
|---|---|---|---|---|    | |
|  A | -  | -  | -  | -   | 0  | - |
|  B | -  | -  | -  | 0  | -  | 100 | 
|  C | -   | -  | -  | 0   | -  | - |
|  D |  - | 0  | 0  | -  | 0  | - |
|  E | 0  |  - |-   | 0  | -  | 100 |
|  F |  - |  0 | -  |  - | 0  | 100 |

 | S/A  | A  | B  | C  | D  |  E  | F |
|---|---|---|---|---|    | |
|  A | -  | -  | -  | -   | 0  | - |
|  B | -  | -  | -  | 0  | -  | 0 | 
|  C | -   | -  | -  | 0   | -  | - |
|  D |  - | 0  | 0  | -  | 0  | - |
|  E | 0  |  - |-   | 0  | -  | 0 |
|  F |  - |  0 | -  |  - | 0  | 0 |

 | S/A  | A  | B  | C  | D  |  E  | F |
|---|---|---|---|---|    | |
|  A | -  | -  | -  | -   | 0  | - |
|  B | -  | -  | -  | 0  | -  | 100 | 
|  C | -   | -  | -  | 0   | -  | - |
|  D |  - | 0  | 0  | -  | 0  | - |
|  E | 0  |  - |-   | 0  | -  | 0 |
|  F |  - |  0 | -  |  - | 0  | 0 |

 | S/A  | A  | B  | C  | D  |  E  | F |
|---|---|---|---|---|    | |
|  A | -  | -  | -  | -   | 0  | - |
|  B | -  | -  | -  | 0  | -  | 100 | 
|  C | -   | -  | -  | 0   | -  | - |
|  D |  - | 80  | 0  | -  | 0  | - |
|  E | 0  |  - |-   | 0  | -  | 0 |
|  F |  - |  0 | -  |  - | 0  | 0 |

 | S/A  | A  | B  | C  | D  |  E  | F |
|---|---|---|---|---|    | |
|  A | -  | -  | -  | -   | 400  | - |
|  B | -  | -  | -  | 320 | -  | 500 | 
|  C | -   | -  | -  | 320   | -  | - |
|  D |  - | 400  | 256 | -  | 400  | - |
|  E | 320  |  - |-   | 320  | -  | 500 |
|  F |  - |  400 | -  |  - | 400  | 500 |